name: Testing Farm test
on:
  pull_request: {}

jobs:
  tests:
    runs-on: [self-hosted, linux, testing-farm]

    steps:
      - uses: actions/checkout@v4
      - name: get message
        run: |
          echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCy2sAVsmqTZOSp3B/+aNwuLuYil5csev6ezn/jJRHrgwV+bwpgqEuN/72aRwFMXZEZEoYAmsVhTOddH52psbcdY8MvP0jK3x/GYXgjHWbjhFzkn3RL8ZesHr6vHkuofOwobX4+z0jgAV6rUBTxyh8n0AUSL+DK2etBiPoM/LXbTmuc7tMTXNeCWAedmpSnzgl0s2QHZVj/C8BHmW5yzKebCLh1EVKrbChQLhuYe0BV4ozLiUNWSGDbppZQlIcJ1rvNAiFbWPxlF/VMinn6n07TSuq4yhFfrgSfsehZZXLUw+lxUPw1nC2HxJsfMTvVzy4mPjwyFtjKVhLGfNvXxi0RpG+aPsXaCvuBaO5ZGFClFbBxEqcJIRoc8CLQc2n7nN1pxjzu7eiStUm5DwkFnWnGu3+yqxTIPWDtDYRzsdXsSy6HqcD0Qjwvh2p83Lel1qU8zn5dZz7yUkGhoHUdAQu4vvvcaK/B7YLBUKw4ROiWxJ+t6BOBVwlWhkQibMK3n70= lul@lul-mac" \
          > ~/.ssh/sshkey.pub
      - name: reserve machine from testing farm
        shell: bash
        env:
          TESTING_FARM_API_TOKEN: ${{ secrets.TESTING_FARM_API_TOKEN }}
        run: |
          echo $TESTING_FARM_API_TOKEN
          export TESTING_FARM_API_TOKEN=$TESTING_FARM_API_TOKEN
          testing-farm reserve --compose Fedora-Rawhide --arch x86_64 --ssh-public-key ~/.ssh/sshkey.pub --no-autoconnect
