name: Testing Farm test
on:
  pull_request: {}

jobs:
  tests:
    runs-on: [self-hosted, linux, testing-farm]

    steps:
      - uses: actions/checkout@v4
      - name: test secret
        shell: bash
        env:
          NAME: ${{ secrets.QUAY_IO_USERNAME }}
        run: |
          echo $NAME
          echo "$NAME"
          echo ${{ NAME }}
          echo ${{ env.NAME }}
